remote: false

experienceLevel:
  internship: false
  entry: true
  associate: true
  mid-senior level: true
  director: false
  executive: false

jobTypes:
  full-time: true
  contract: true
  part-time: true
  temporary: true
  internship: false
  other: true
  volunteer: true

date:
  all time: false
  month: false
  week: false
  24 hours: true

positions:
  - Software engineer
  - Software developer

locations:
  - Canada

apply_once_at_company: false

distance: 100

company_blacklist:
  - Google
  - Amazon
  - Meta

title_blacklist:
  - Senior
  - Embedded

job_applicants_threshold:
  min_applicants: 0
  max_applicants: 3000

llm_model_type: openai
llm_model: "gpt-4o-mini"
# llm_api_url: 'https://api.pawan.krd/cosmosrp/v1'
