name: Label Merged PRs

on:
  pull_request:
    types: [closed]

jobs:
  label-merged-pr:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest

    steps:
      - name: Add label
        if: startsWith(github.event.pull_request.base.ref, 'release/')
        uses: actions-ecosystem/action-add-labels@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          labels: merged-to-release